version: "3.7"

services:
  zookeeper-server:
    build:
      context: .
      target: zookeeper-server

  kafka-server:
    build:
      context: .
      target: kafka-server
    command: "--override zookeeper.connect=zookeeper-server"

  kafka-producer:
    image: mozilla/sbt
    volumes:
      - ./GDELTProducer:/app
    command: sbt run
    working_dir: /app

  kafka-stream:
    image: mozilla/sbt
    volumes:
      - ./GDELTStream:/app
    command: sbt ~run
    working_dir: /app

  kafka-consumer:
    image: mozilla/sbt
    volumes:
      - ./GDELTConsumer:/app
    command: sbt run
    working_dir: /app
    ports:
      - "1337:1337"

  kafka-console-consumer:
    build:
      context: .
      target: kafka-console-consumer
    command: "--bootstrap-server kafka-server:9092 --topic gdelt-histogram --property print.key=true"

  visualizer:
    build:
      context: .
      target: visualizer
    volumes:
      - ./GDELTVisualizer:/src
    ports:
      - "1234:1234"
      - "12345:12345"
