name: Manual

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install mdbook
      run: |
        mkdir -p $HOME/mdbook
        curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.2/mdbook-v0.4.2-x86_64-unknown-linux-gnu.tar.gz | tar xz -C $HOME/mdbook
        echo "::add-path::${HOME}/mdbook/"
    - name: Build
      run: mdbook build
    - uses: peaceiris/actions-gh-pages@v3
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: book
