name: Manual

on:
  push:
    branches:
    - master
    - staging
    - trying
  pull_request:

env:
  MDBOOK: '0.4.12'
  LINKCHECK: '0.7.4'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install mdbook
      run: curl -L https://github.com/rust-lang/mdBook/releases/download/v$MDBOOK/mdbook-v$MDBOOK-x86_64-unknown-linux-gnu.tar.gz | tar xz -C ~/.cargo/bin
    - name: Install mdbook-linkcheck
      run: |
        wget -qO mdbook-linkcheck.zip https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/v$LINKCHECK/mdbook-linkcheck.v$LINKCHECK.x86_64-unknown-linux-gnu.zip
        unzip mdbook-linkcheck.zip -d ~/.cargo/bin
        chmod +x ~/.cargo/bin/mdbook-linkcheck
    - name: Build
      run: mdbook build
    - uses: peaceiris/actions-gh-pages@v3
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: book
